import React from 'react';
import Head from 'next/head';
import SEO from '../components/SEO';

// Test page to demonstrate SEO component functionality
export default function TestSEO() {
  return (
    <div>
      <SEO
        title="SEO Test Page"
        description="This page demonstrates the SEO component with all features including OpenGraph, Twitter Cards, and JSON-LD structured data."
        url="https://example.com/test"
        image="https://example.com/image.jpg"
        siteName="Test Blog"
        twitterHandle="testuser"
        keywords={["seo", "nextjs", "hashnode", "blog"]}
        article={{
          publishedTime: "2024-01-01T00:00:00Z",
          author: "Test Author",
          tags: ["seo", "web development"]
        }}
      />
      
      <main style={{ padding: '2rem', fontFamily: 'Arial, sans-serif' }}>
        <h1>SEO Component Test Page</h1>
        
        <section>
          <h2>What this page demonstrates:</h2>
          <ul>
            <li>✅ Page title optimization (max 60 chars)</li>
            <li>✅ Meta description optimization (max 160 chars)</li>
            <li>✅ OpenGraph tags for social media sharing</li>
            <li>✅ Twitter Card tags</li>
            <li>✅ Canonical URL</li>
            <li>✅ JSON-LD structured data</li>
            <li>✅ Article-specific meta tags</li>
            <li>✅ Keywords meta tag</li>
          </ul>
        </section>

        <section>
          <h2>View Page Source</h2>
          <p>
            Right-click and "View Page Source" to see all the SEO meta tags that have been automatically generated by the SEO component.
          </p>
        </section>

        <section>
          <h2>Test with SEO Tools</h2>
          <p>Use these tools to test the SEO implementation:</p>
          <ul>
            <li><strong>Facebook Debugger:</strong> https://developers.facebook.com/tools/debug/</li>
            <li><strong>Twitter Card Validator:</strong> https://cards-dev.twitter.com/validator</li>
            <li><strong>LinkedIn Post Inspector:</strong> https://www.linkedin.com/post-inspector/</li>
            <li><strong>Google Rich Results Test:</strong> https://search.google.com/test/rich-results</li>
          </ul>
        </section>
      </main>
    </div>
  );
}